name: macOS Build (Electron, unsigned)

on:
  workflow_dispatch: {}

jobs:
  build-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [arm64]            # add x64 later if you need both

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install deps
        run: npm ci || npm i

      - name: Build web bundle (Vite)
        run: npm run build

      # Create build/icon.icns ONLY if your PNG exists in the repo
      - name: Create mac .icns from PNG (if present)
        if: ${{ hashFiles('build/BattenMajorMatch-icon-1024.png') != '' }}
        shell: bash
        run: |
          mkdir -p build/Icon.iconset
          sips -z 16 16     build/BattenMajorMatch-icon-1024.png --out build/Icon.iconset/icon_16x16.png
          sips -z 32 32     build/BattenMajorMatch-icon-1024.png --out build/Icon.iconset/icon_16x16@2x.png
          sips -z 32 32     build/BattenMajorMatch-icon-1024.png --out build/Icon.iconset/icon_32x32.png
          sips
